# Define a imagem base
FROM node:14-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o package.json e o package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o restante dos arquivos do projeto para o diretório de trabalho
COPY . .

# Define a porta em que o aplicativo estará ouvindo dentro do contêiner
EXPOSE 3000

# Define o comando padrão para iniciar o aplicativo
CMD [ "npm", "start" ]
